/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AusgabenTypEditor.java
 *
 * Created on Jan 4, 2013, 12:03:22 PM
 */
package dsh;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maak
 */
public class AusgabenTypEditor extends javax.swing.JFrame {
        private DefaultTableModel myATtable;
        private int colContainingID=0;
        private Model myModel;
        private AusgabenTyp myAusgabenTyp;

    /** Creates new form AusgabenTypEditor */
    public AusgabenTypEditor() {
        initComponents();
        initAusgabenTypEditor ();
    }
    
    public void initAusgabenTypEditor (){
        myModel=DshApp.getModel();
        myAusgabenTyp = new AusgabenTyp ();
        refreshATtable();
        loadATintoEditor();
    }
    
    private void refreshATtable () {
        myATtable=myModel.getTableAusgabenTyp();
        if (myATtable!=null) {
            tableExistingAusgbenTypen.setModel(myATtable);
            tableExistingAusgbenTypen.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            TableModelHelper.packColumns(tableExistingAusgbenTypen);
        } else {
            JOptionPane.showMessageDialog(this, "Tabelle Ausgabe-Typ konnte NICHT geladen werden!");
        }
    }
    
    private void loadATintoEditor (){
        if (myAusgabenTyp.getId()==-1 || myAusgabenTyp.isAusgabenTypSuccesfullyLoaded()) {
            textFieldAusgabenTypName.setText(myAusgabenTyp.getAtName());
            checkBoxBudgetNeutral.setSelected(myAusgabenTyp.isBudgetNeutral());
        } else {
            JOptionPane.showMessageDialog(this, "Ausgabe-Typ konnte NICHT geladen werden!");
        }       
    }
    
    private String errorOnFillingEntriesIntoAT () {
        String entriesValidationError = "";
        if (textFieldAusgabenTypName.getText().equals("")) entriesValidationError="Bezeichnerfeld ist leer.";
        return entriesValidationError;
    }
    private boolean succesfullySavedDataToDB () {
        String fieldsErrorCode = errorOnFillingEntriesIntoAT(); // Einträge valide?
        if (fieldsErrorCode.equals("")) { 
            myAusgabenTyp.setAtName(textFieldAusgabenTypName.getText());
            myAusgabenTyp.setBudgetNeutral(checkBoxBudgetNeutral.isSelected());
            return myAusgabenTyp.successfullySavedToDB(); // Budget Objekt kümmert sich ums speichern
        } else {
           JOptionPane.showMessageDialog(this, fieldsErrorCode+": Bitte überprüfen Sie Ihre Eingabe.");
           System.out.println ("** Eingabefehler: "+fieldsErrorCode);
        }
        return false;
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableExistingAusgbenTypen = new javax.swing.JTable();
        buttonEdit = new javax.swing.JButton();
        buttonLoeschen = new javax.swing.JButton();
        textFieldAusgabenTypName = new javax.swing.JTextField();
        buttonSpeichern = new javax.swing.JButton();
        buttonSchliessen = new javax.swing.JButton();
        buttonNeu = new javax.swing.JButton();
        checkBoxBudgetNeutral = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dsh.DshApp.class).getContext().getResourceMap(AusgabenTypEditor.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableExistingAusgbenTypen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableExistingAusgbenTypen.setName("tableExistingAusgbenTypen"); // NOI18N
        jScrollPane2.setViewportView(tableExistingAusgbenTypen);

        buttonEdit.setText(resourceMap.getString("buttonEdit.text")); // NOI18N
        buttonEdit.setName("buttonEdit"); // NOI18N
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonLoeschen.setText(resourceMap.getString("buttonLoeschen.text")); // NOI18N
        buttonLoeschen.setName("buttonLoeschen"); // NOI18N
        buttonLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoeschenActionPerformed(evt);
            }
        });

        textFieldAusgabenTypName.setText(resourceMap.getString("textFieldAusgabenTypName.text")); // NOI18N
        textFieldAusgabenTypName.setName("textFieldAusgabenTypName"); // NOI18N

        buttonSpeichern.setText(resourceMap.getString("buttonSpeichern.text")); // NOI18N
        buttonSpeichern.setName("buttonSpeichern"); // NOI18N
        buttonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpeichernActionPerformed(evt);
            }
        });

        buttonSchliessen.setText(resourceMap.getString("buttonSchliessen.text")); // NOI18N
        buttonSchliessen.setName("buttonSchliessen"); // NOI18N
        buttonSchliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSchliessenActionPerformed(evt);
            }
        });

        buttonNeu.setText(resourceMap.getString("buttonNeu.text")); // NOI18N
        buttonNeu.setName("buttonNeu"); // NOI18N
        buttonNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNeuActionPerformed(evt);
            }
        });

        checkBoxBudgetNeutral.setText(resourceMap.getString("checkBoxBudgetNeutral.text")); // NOI18N
        checkBoxBudgetNeutral.setName("checkBoxBudgetNeutral"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(18, 18, 18)
                                .add(buttonSchliessen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(buttonEdit)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(buttonLoeschen)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 101, Short.MAX_VALUE)
                                .add(buttonNeu))
                            .add(jScrollPane2, 0, 0, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(checkBoxBudgetNeutral)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                        .add(buttonSpeichern, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel5))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(textFieldAusgabenTypName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonSchliessen))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonEdit)
                    .add(buttonLoeschen)
                    .add(buttonNeu))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .add(2, 2, 2)
                .add(textFieldAusgabenTypName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checkBoxBudgetNeutral)
                    .add(buttonSpeichern))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (tableExistingAusgbenTypen.getSelectedRow()!=-1) {
                if (myAusgabenTyp.getId()>0) myAusgabenTyp.disposeMe();
                myAusgabenTyp = new AusgabenTyp (
                         ((java.lang.Integer) tableExistingAusgbenTypen.getValueAt(
                                tableExistingAusgbenTypen.getSelectedRow(),
                                colContainingID)
                         ).intValue()
                        );
            }
            loadATintoEditor();            
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSchliessenActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (myAusgabenTyp.getId()>0) myAusgabenTyp.disposeMe();
            DshApp.getApplication().ausgabenTypEditorEnd();            
        }
    }//GEN-LAST:event_buttonSchliessenActionPerformed

    private void buttonLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoeschenActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this) && DshApp.getApplication().userAccordOnDeleteWarning(this)) {
            if (tableExistingAusgbenTypen.getSelectedRow()!=-1) {
                int selectedForDelete =((java.lang.Integer)
                        tableExistingAusgbenTypen.getValueAt(
                            tableExistingAusgbenTypen.getSelectedRow(),
                            colContainingID)
                        ).intValue();
                if (selectedForDelete==myAusgabenTyp.getId()) {
                    // if to-be-deleted AT is the loaded one..
                    myAusgabenTyp.deleteAT();
                    initAusgabenTypEditor();
                } else {
                    AusgabenTyp.deleteAT(selectedForDelete);
                    refreshATtable ();
                }

            }            
        }
    }//GEN-LAST:event_buttonLoeschenActionPerformed

    private void buttonNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNeuActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (myAusgabenTyp.getId()>0) myAusgabenTyp.disposeMe();
            myAusgabenTyp = new AusgabenTyp ();
            loadATintoEditor ();                    
        }
    }//GEN-LAST:event_buttonNeuActionPerformed

    private void buttonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpeichernActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (!succesfullySavedDataToDB()) JOptionPane.showMessageDialog(this, "Ausgabe-Typ konnte NICHT gespeichert werden!");
            refreshATtable ();            
        }
    }//GEN-LAST:event_buttonSpeichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AusgabenTypEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AusgabenTypEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AusgabenTypEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AusgabenTypEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AusgabenTypEditor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonLoeschen;
    private javax.swing.JButton buttonNeu;
    private javax.swing.JButton buttonSchliessen;
    private javax.swing.JButton buttonSpeichern;
    private javax.swing.JCheckBox checkBoxBudgetNeutral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableExistingAusgbenTypen;
    private javax.swing.JTextField textFieldAusgabenTypName;
    // End of variables declaration//GEN-END:variables
}
