/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KontoEditor.java
 *
 * Created on Jan 4, 2013, 12:03:22 PM
 */
package dsh;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maak
 */
public class KontoEditor extends javax.swing.JFrame {
        private DefaultTableModel myKontotable;
        private int colContainingID=0;
        private Model myModel;
        private Konto myKonto;

    /** Creates new form KontoEditor */
    public KontoEditor() {
        initComponents();
        initKontoEditor ();
    }
    
    public void initKontoEditor (){
        myModel=DshApp.getModel();
        myKonto = new Konto ();
        refreshKontotable();
        loadKontointoEditor();
    }
    
    private void refreshKontotable () {
        myKontotable=myModel.getTableKonto();
        if (myKontotable!=null) {
            tableExistingKonten.setModel(myKontotable);
            tableExistingKonten.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            TableModelHelper.packColumns(tableExistingKonten);
        } else {
            JOptionPane.showMessageDialog(this, "Tabelle Ausgabe-Typ konnte NICHT geladen werden!");
        }
    }
    
    private void loadKontointoEditor (){
        if (myKonto.getId()==-1 || myKonto.isKontoSuccesfullyLoaded()) {
            textFieldKontoName.setText(myKonto.getKontoName());
            checkBoxEigentum.setSelected(myKonto.isEigentum());
            checkBoxPositiv.setSelected(myKonto.isPositiv());
        } else {
            JOptionPane.showMessageDialog(this, "Ausgabe-Typ konnte NICHT geladen werden!");
        }       
    }
    
    private String errorOnFillingEntriesIntoKonto () {
        String entriesValidationError = "";
        if (textFieldKontoName.getText().equals("")) entriesValidationError="Bezeichnerfeld ist leer.";
        return entriesValidationError;
    }
    private boolean succesfullySavedDataToDB () {
        String fieldsErrorCode = errorOnFillingEntriesIntoKonto(); // Einträge valide?
        if (fieldsErrorCode.equals("")) { 
            myKonto.setKontoName(textFieldKontoName.getText());
            myKonto.setEigentum(checkBoxEigentum.isSelected());
            myKonto.setPositiv(checkBoxPositiv.isSelected());
            return myKonto.successfullySavedToDB(); // Budget Objekt kümmert sich ums speichern
        } else {
           JOptionPane.showMessageDialog(this, fieldsErrorCode+": Bitte überprüfen Sie Ihre Eingabe.");
           System.out.println ("** Eingabefehler: "+fieldsErrorCode);
        }
        return false;
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableExistingKonten = new javax.swing.JTable();
        buttonEdit = new javax.swing.JButton();
        buttonLoeschen = new javax.swing.JButton();
        textFieldKontoName = new javax.swing.JTextField();
        buttonSpeichern = new javax.swing.JButton();
        buttonSchliessen = new javax.swing.JButton();
        buttonNeu = new javax.swing.JButton();
        checkBoxEigentum = new javax.swing.JCheckBox();
        checkBoxPositiv = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dsh.DshApp.class).getContext().getResourceMap(KontoEditor.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableExistingKonten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableExistingKonten.setName("tableExistingKonten"); // NOI18N
        jScrollPane2.setViewportView(tableExistingKonten);

        buttonEdit.setText(resourceMap.getString("buttonEdit.text")); // NOI18N
        buttonEdit.setName("buttonEdit"); // NOI18N
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonLoeschen.setText(resourceMap.getString("buttonLoeschen.text")); // NOI18N
        buttonLoeschen.setName("buttonLoeschen"); // NOI18N
        buttonLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoeschenActionPerformed(evt);
            }
        });

        textFieldKontoName.setText(resourceMap.getString("textFieldKontoName.text")); // NOI18N
        textFieldKontoName.setName("textFieldKontoName"); // NOI18N

        buttonSpeichern.setText(resourceMap.getString("buttonSpeichern.text")); // NOI18N
        buttonSpeichern.setName("buttonSpeichern"); // NOI18N
        buttonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpeichernActionPerformed(evt);
            }
        });

        buttonSchliessen.setText(resourceMap.getString("buttonSchliessen.text")); // NOI18N
        buttonSchliessen.setName("buttonSchliessen"); // NOI18N
        buttonSchliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSchliessenActionPerformed(evt);
            }
        });

        buttonNeu.setText(resourceMap.getString("buttonNeu.text")); // NOI18N
        buttonNeu.setName("buttonNeu"); // NOI18N
        buttonNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNeuActionPerformed(evt);
            }
        });

        checkBoxEigentum.setText(resourceMap.getString("checkBoxEigentum.text")); // NOI18N
        checkBoxEigentum.setName("checkBoxEigentum"); // NOI18N

        checkBoxPositiv.setText(resourceMap.getString("checkBoxPositiv.text")); // NOI18N
        checkBoxPositiv.setName("checkBoxPositiv"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(textFieldKontoName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(20, 20, 20)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jLabel1)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 113, Short.MAX_VALUE)
                                    .add(buttonSchliessen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(buttonEdit)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(buttonLoeschen)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 98, Short.MAX_VALUE)
                                    .add(buttonNeu))
                                .add(jScrollPane2, 0, 0, Short.MAX_VALUE)))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(checkBoxEigentum))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(checkBoxPositiv)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 134, Short.MAX_VALUE)
                            .add(buttonSpeichern, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buttonSchliessen))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonEdit)
                    .add(buttonLoeschen)
                    .add(buttonNeu))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .add(3, 3, 3)
                .add(textFieldKontoName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(checkBoxEigentum)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checkBoxPositiv)
                    .add(buttonSpeichern))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (tableExistingKonten.getSelectedRow()!=-1) {
                if (myKonto.getId()>0) myKonto.disposeMe();
                myKonto = new Konto (
                         ((java.lang.Integer) tableExistingKonten.getValueAt(
                                tableExistingKonten.getSelectedRow(),
                                colContainingID)
                         ).intValue()
                        );
            }
            loadKontointoEditor();            
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSchliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSchliessenActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (myKonto.getId()>0) myKonto.disposeMe();
            DshApp.getApplication().endKontoEditor();            
        }
    }//GEN-LAST:event_buttonSchliessenActionPerformed

    private void buttonLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoeschenActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (tableExistingKonten.getSelectedRow()!=-1) {
                int selectedForDelete =((java.lang.Integer)
                        tableExistingKonten.getValueAt(
                            tableExistingKonten.getSelectedRow(),
                            colContainingID)
                        ).intValue();
                if (selectedForDelete==myKonto.getId()) {
                    // if to-be-deleted Konto is the loaded one..
                    myKonto.deleteKonto();
                    initKontoEditor();
                } else {
                    Konto.deleteKonto(selectedForDelete);
                    refreshKontotable ();
                }

            }            
        }
    }//GEN-LAST:event_buttonLoeschenActionPerformed

    private void buttonNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNeuActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (myKonto.getId()>0) myKonto.disposeMe();
            myKonto = new Konto ();
            loadKontointoEditor ();                    
        }
    }//GEN-LAST:event_buttonNeuActionPerformed

    private void buttonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpeichernActionPerformed
        if (DshApp.getApplication().isTheTopWindow(this)) {
            if (!succesfullySavedDataToDB()) JOptionPane.showMessageDialog(this, "Ausgabe-Typ konnte NICHT gespeichert werden!");
            refreshKontotable ();            
        }
    }//GEN-LAST:event_buttonSpeichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KontoEditor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonLoeschen;
    private javax.swing.JButton buttonNeu;
    private javax.swing.JButton buttonSchliessen;
    private javax.swing.JButton buttonSpeichern;
    private javax.swing.JCheckBox checkBoxEigentum;
    private javax.swing.JCheckBox checkBoxPositiv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableExistingKonten;
    private javax.swing.JTextField textFieldKontoName;
    // End of variables declaration//GEN-END:variables
}
