/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableViewer.java
 *
 * Created on Jun 24, 2012, 8:32:06 PM
 */
package dsh;
import javax.swing.ListSelectionModel;
import javax.swing.table.*;

/**
 *
 * @author maak
 */
public class TableViewer extends javax.swing.JFrame {
    private DefaultTableModel myData;
    private int colContainingID=-1;

    /** Creates new form TableViewer */
    public TableViewer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myMainTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        buttenEdit = new javax.swing.JButton();
        loeschenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        myMainTable.setAutoCreateRowSorter(true);
        myMainTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        myMainTable.setFocusable(false);
        myMainTable.setName("myMainTable"); // NOI18N
        jScrollPane1.setViewportView(myMainTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dsh.DshApp.class).getContext().getResourceMap(TableViewer.class);
        refreshButton.setText(resourceMap.getString("refreshButton.text")); // NOI18N
        refreshButton.setName("refreshButton"); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refresh_pressed(evt);
            }
        });

        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ok_pressed(evt);
            }
        });

        buttenEdit.setText(resourceMap.getString("buttenEdit.text")); // NOI18N
        buttenEdit.setName("buttenEdit"); // NOI18N
        buttenEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttenEditActionPerformed(evt);
            }
        });

        loeschenButton.setText(resourceMap.getString("loeschenButton.text")); // NOI18N
        loeschenButton.setName("loeschenButton"); // NOI18N
        loeschenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loeschenButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(buttenEdit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(loeschenButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 444, Short.MAX_VALUE)
                        .add(refreshButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(refreshButton)
                    .add(buttenEdit)
                    .add(loeschenButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ok_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ok_pressed
        // TODO add your handling code here:
        DshApp.getApplication().EndListBuchungen();
    }//GEN-LAST:event_button_ok_pressed

    private void button_refresh_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refresh_pressed
        DshApp.getApplication().updateListBuchungen();
        myMainTable.setModel(this.myData);
        myMainTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableModelHelper.packColumns(myMainTable,4);
    }//GEN-LAST:event_button_refresh_pressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        // this.dispose ();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        // this.dispose ();
    }//GEN-LAST:event_formWindowClosed

    private void buttenEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttenEditActionPerformed
        if (this.myMainTable.getSelectedRow()!=-1) {
            DshApp.getApplication().StartBuchungsEditor(
                        ((java.lang.Integer) this.myMainTable.getValueAt(
                            this.myMainTable.getSelectedRow(),
                            this.colContainingID
                        )).intValue()
                    );
        }
    }//GEN-LAST:event_buttenEditActionPerformed

    private void loeschenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loeschenButtonActionPerformed
        if (this.myMainTable.getSelectedRow()!=-1) {
            DshApp.getApplication().deleteBuchung(this,
                        ((java.lang.Integer) this.myMainTable.getValueAt(
                            this.myMainTable.getSelectedRow(),
                            this.colContainingID
                        )).intValue()                  
                    );
            button_refresh_pressed(null);
        }        
    }//GEN-LAST:event_loeschenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TableViewer().setVisible(true);
            }
        });
    }
    
    public void initTableViewer (DefaultTableModel data, int colWithID) {
        this.myData=data;
        this.colContainingID=colWithID;
        myMainTable.setModel(this.myData);
        TableModelHelper.packColumns(myMainTable);
        // myMainTable.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttenEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loeschenButton;
    private javax.swing.JTable myMainTable;
    private javax.swing.JButton okButton;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
